=== myplusher/StAX-LR/src/main/resources/state.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:rt="http://namespacedmitriev.com/State"
           targetNamespace="http://namespacedmitriev.com/State"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="root">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="states" type="rt:States"/>
                <xs:element name="location" type="rt:Location" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="Device">
        <xs:attribute name="id" type="xs:unsignedInt" use="required"/>
        <xs:attribute name="device_name" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="Location">
        <xs:sequence>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="sensor" type="rt:Sensor" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="device" type="rt:Device" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:unsignedInt" use="required"/>
        <xs:attribute name="location_type" type="xs:string" use="required"/>
        <xs:attribute name="square" type="xs:decimal"/>
        <xs:attribute name="address" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="Sensor">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:unsignedInt" use="required"/>
    </xs:complexType>
    <xs:complexType name="States">
        <xs:sequence>
            <xs:element name="state" type="rt:State" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="State">
        <xs:sequence>
            <xs:element name="sensor_value" type="rt:Sensor_value" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="time" type="xs:dateTime"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:unsignedInt" use="required"/>
    </xs:complexType>
    <xs:complexType name="Sensor_value">
        <xs:sequence>
            <xs:element name="sid" type="xs:int"/>
            <xs:element name="value" type="xs:int"/>
        </xs:sequence>
        <xs:attribute name="data_type" type="xs:string" use="required"/>
    </xs:complexType>
</xs:schema>

=== myplusher/StAX-LR/src/main/resources/state.xml
<?xml version="1.0" encoding="UTF-8" ?>
<root xmlns="http://namespacedmitriev.com/State"
     xsi:schemaLocation="http://namespacedmitriev.com/State state.xsd"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <states>
       <state id="1">
           <sensor_value data_type="Влажность в процентах">
               <sid>1</sid>
               <value>70</value>
           </sensor_value>
           <sensor_value data_type="Температура в градусах">
               <sid>2</sid>
               <value>22</value>
           </sensor_value>
           <time>2022-06-05T20:32:12</time>
       </state>
       <state id="2">
           <sensor_value data_type="Влажность в процентах">
               <sid>1</sid>
               <value>80</value>
           </sensor_value>
           <sensor_value data_type="Температура в градусах">
               <sid>2</sid>
               <value>23</value>
           </sensor_value>
           <time>2022-06-04T20:32:12</time>
       </state>
   </states>
    <location id="1" location_type="древообрабатывающий" address="Владимир, Сладкого" square="10">
        <description>Деревообрабатывающий цех (ДЦ) предназначен для изготовления досок из цельных стволов дерева и их обработки. Данный цех является частью комбината, осуществляющего производство мебели. Деревообрабатывающий цех имеет собственную комплектную трансформаторную подстанцию (КТП).</description>
        <sensor id="1">
            <name>Гигрометр</name>
        </sensor>
        <sensor id="2">
            <name>Термометр</name>
        </sensor>
        <device id="1" device_name="кондиционер"/>
        <device id="2" device_name="увлажнитель"/>
    </location>
    <location id="2" location_type="электро" address="Владимир, Горького" square="100.5">
        <description>Минимальная допустимая площадь серверной — 12 кв. м. Потолок помещения должен иметь высоту как минимум 2,44 м. Рассчитывая площадь комнаты на этапе её проектирования, нужно учитывать то, сколько оборудования в ней будет установлено, и сколько сотрудников работать. Рекомендуется отводить под серверную комнату помещение, не имеющее окон. Если это условие соблюдается, оборудование получит дополнительную защиту от солнечного света и несанкционированного проникновения. Высота двери должна составлять как минимум 2 м, ширина — как минимум 0,91 м. Дверь должна раздвигаться или открываться наружу, в ней должен быть надёжный замок.</description>
        <sensor id="1">
            <name>Термометр</name>
        </sensor>
        <device id="2" device_name="кондиционер"/>
    </location>
</root>
